version: '3'
services:

  nginx1:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/nginx.conf
    depends_on:
      - php1
      - db

  nginx2:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf
    depends_on:
      - php2
      - db
  php1:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./first_project/:/var/www/html
    depends_on:
      - db
  php2:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./second_project/:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/mysql
